- name: "Hot Dogs"
  icon: "cutlery"
  description: "We offer Hot Dogs."

- name: "Water"
  icon: "tint"
  description: "We offer bottled water, cold."

- name: "Chips"
  icon: "cutlery"
  description: "We also offer chips."
